config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post 'apostas', to: 'pages#apostas'
  get 'sorte', to: 'pages#sorte'
  get 'conjuntos', to: 'pages#conjuntos'
  get 'estatistica', to: 'pages#estatistica'

  # resources :sorteios

  get 'sorteios', to: 'sorteios#index'
  post 'sorteios', to: 'sorteios#create'
  get 'sorteios/new', to: 'sorteios#new'
  get 'sorteios/:id', to: 'sorteios#show', as: 'sorteio'
  get 'sorteios/:id/edit', to: 'sorteios#edit', as: 'edit_sorteio'
  patch 'sorteios/:id', to: 'sorteios#update'
  delete 'sorteios/:id', to: 'sorteios#destroy'

end

app/models/sorteio.rb
class Sorteio < ApplicationRecord
end

app/controllers/sorteios_controller.rb
class SorteiosController < ApplicationController
  

  def index
    # @sorteios = Sorteio.all
    @sorteios = policy_scope(Sorteio)
  end
  
  def show
    @sorteio = Sorteio.find(params[:id])
    authorize @sorteio  
 
  end

  def new
    @sorteio = Sorteio.new # Needed to instantiate the form_with
    authorize @sorteio
  end

  
  def create

    @sorteio = Sorteio.new()

    @sorteio.concurso = params[:sorteio][:concurso].to_i
    @sorteio.data = params[:sorteio][:data].to_time.strftime('%d/%m/%Y')
    @sorteio.numeros = params[:sorteio][:numeros]

    authorize @sorteio

    @sorteio.save
    # No need for app/views/sorteios/create.html.erb
    redirect_to sorteio_path(@sorteio)
  end
  
  def edit
    @sorteio = Sorteio.find(params[:id])
    authorize @sorteio
  end

  def update
    @sorteio = Sorteio.find(params[:id])
    authorize @sorteio
    @sorteio.update({concurso: params[:sorteio][:concurso].to_i, data: params[:sorteio][:data].to_time.strftime('%d/%m/%Y'), numeros: params[:sorteio][:numeros]})

    # No need for app/views/sorteios/update.html.erb
    redirect_to sorteio_path(@sorteio)
  end

  def destroy
    
    @sorteio = Sorteio.find(params[:id])
    authorize @sorteio
    @sorteio.destroy
    # No need for app/views/sorteios/destroy.html.erb
    redirect_to sorteios_path, status: :see_other
  end

  # private
  
  # def sorteio_params
  #   params.require(:sorteio).permit(:concurso, :data, :numeros)
  #   # params[:sorteio][:data] = Time.strptime(params[:sorteio][:data], "%Y-%m-%d").strftime("%d/%m/%Y")  
  #   # params[:sorteio][:data] = params[:sorteio][:data].to_time.strftime('%d/%m/%Y')
  # end


end

app/views/sorteios/edit.html.erb
<%= form_with model: @sorteio do |f| %>
  <%= f.label :concurso %>
  <%= f.number_field :concurso %>
  <%= f.label :data %>
  <%= f.text_field :data %> <!--retirei o date_field porque estava dando erro. Tentei resolver trocando o ":data" por "@sorteio.data.to_time", mas o update não funcionava. O problema todo é porque o form with tenta converter, por padrão, o dado que é string em strftime com Y-m-d e isso dá um erro -->
  <%= f.label :numeros %>
  <%= f.text_field :numeros %>
  <%= f.submit %>
<% end %>
<br>
<br>
<p>
  <%= link_to "Todos os sorteios", sorteios_path, method: "get" %>
</p>

app/views/sorteios/index.html.erb
<h1>INDEX FUNCIONANDO (ROOT/sorteios)</h1>

<h1>TOTAL DE SORTEIOS: <%= @sorteios.size %></h1> <%# outras opções .length OU .count   TESTAR %>
<%= link_to 'Inserir NOVO SORTEIO', sorteios_new_path, method: "get" %>


<ul>
  <% @sorteios.reverse().each do |sorteio|  %>
    <li><%= link_to "concurso: #{sorteio.concurso}; data: #{sorteio.data}; números: #{sorteio.numeros}", sorteio_path(sorteio), method: "get" %></li>
  <% end %>
</ul>

<p>
<%= Time.parse('2007-01-31') %>
</p>
<p>
<%= Time.strptime("2000-10-31", "%Y-%m-%d").strftime("%d/%m/%Y") %>
</p>

app/views/sorteios/new.html.erb
<%= form_with model: @sorteio do |f| %>
  <%= f.label :concurso %>
  <%= f.number_field :concurso %>
  <%= f.label :data %>
  <%= f.date_field :data %>
  <%= f.label :numeros %>
  <%= f.text_field :numeros %>
  <%= f.submit %>
<% end %>
<br>
<br>
<%= link_to "Todos os sorteios", sorteios_path, method: "get" %>

app/views/sorteios/show.html.erb
<%= link_to "Todos os sorteios", sorteios_path, method: "get" %>

<h2><%= @sorteio.concurso %></h2>
<p><%= @sorteio.data %></p>
<p><%= @sorteio.numeros %></p>

<p>
  <%= link_to "Editar", edit_sorteio_path(@sorteio) %>
</p>

<p>
  <%= link_to "Apagar",
    sorteio_path,
    method: :delete, data: {confirm: "Apagar sorteio?"}
  %>
</p>